config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :posts  do
=begin
    collection do
      get 'search'
    end
=end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  resources :relationships, only: [:create, :destroy, :index]

  get 'tags/:tag' => 'posts#tags', :as => 'tag'
  get 'articles/:author' => 'posts#articles', :as => 'article'

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  acts_as_votable
  acts_as_taggable_on :tags
  is_impressionable


  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 250 }
  validates :category, presence: true
  validates :tag_list, presence: true

  friendly_id :title,use: [:slugged, :history]

  def should_generate_new_friendly_id?
    title_changed? ||new_record? || slug.nil? || slug.blank?
  end


  has_attached_file :image, :styles => { :large => '900x300>',
                                         :medium => '300x300#',
                                         :square => '200x200#',
                                         :thumb => '100x100>' ,
                    :default_url => "/images/:style/missing.png"}

  validates_attachment_content_type :image,
                                    :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_many :comments
  belongs_to :category



  def score
    self.get_upvotes.size - self.get_downvotes.size
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :articles]
  before_filter :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  impressionist :actions=>[:show,:index]

  def index
    #@posts = Post.order('created_at DESC').page(params[:page]).per(3)
    if params[:category].blank?
      @posts = Post.all.order('created_at DESC').page(params[:page]).per(10)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order('created_at DESC').page(params[:page]).per(10)
    end

  end
  def show

    if request.path != post_path(@post)
      redirect_to @post, :status => :moved_permanently
    end

    @comments = Comment.where(post_id: @post.id).order('created_at DESC')
    @related_articles = Post.tagged_with(@post.tag_list, any: true).order('created_at DESC').page(params[:page]).per(2)
    impressionist(@post)

    @user = @post.user
    @latest_posts = Post.where(user_id: @user.id).order('created_at DESC').limit(5)
  end
  def new
    @post = Post.new
    #@categories = Category.all.map{|c| [ c.name, c.id ] }
  end
  def create
    @user = current_user
    @post = @user.posts.build(allowed_params)
   # @post.category_id = params[:category_id]

    if @post.save
      flash[:success] = 'New Post Created'
      redirect_to @post
    else
      render 'new'
    end
  end
  def edit
    redirect_to posts_path unless @post.user == current_user
   # @categories = Category.all.map{|c| [ c.name, c.id ] }
  end
  def update
    if @post.user == current_user
      if @post.update_attributes(allowed_params)
        flash[:success] = 'Updated post'
        redirect_to @post
      else
        render 'edit'
      end
    else
      redirect_to posts_path
      flash[:notice] = 'Action Failed!'
    end
    #@post.category_id = params[:category_id]
  end
  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to posts_path
    else
      redirect_to root_path
      flash[:danger] = 'Action Failed!'
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  def tags
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end
    def articles
      @user = User.find(params[:author])
    if params[:author].present?
      @articles = Post.where(user_id: @user).order('created_at DESC').page(params[:page]).per(10)
    end
  end

  private
  def allowed_params
    params.require(:post).permit(:image, :caption, :title, :excerpt, :body, :category_id, :tag_list, :author)
  end
  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/posts/section/_about.html.erb
<div class='well well-sm'>
  <div class='media'>

    <%= link_to user_path(@post.user), class:'thumbnail pull-left' do %>
        <%= image_tag(@post.user.avatar.url(:thumb),class:'media-object',style:'width:100px;height:100px') %>
    <% end %>

    <div class='media-body '>
      <h4 class='media-heading'>&nbsp;&nbsp;<%= @post.user.name.titleize %></h4>
      <% if @post.user.skill %>
      <p class=''> &nbsp;&nbsp;<%= @post.user.skill.titleize %></p>
          <% end %>
      <%=link_to  article_path(@user.id) do %>
          <p><span class='label label-info'><%= @user.posts.count %> posts
      <%end%></span>

      <span class='label label-primary'><%= @user.received_invites.count %> followers</span>
            <span class="">
            <% if @post.score == 0 %>
                <%= link_to  like_post_path(@post), method: :put, class:'btn btn-xs btn-default' do %>
                    <i class='glyphicon glyphicon-heart'></i> Like <%end%>
            <% else %>
                <%= link_to  like_post_path(@post), method: :put, class:'btn btn-xs btn-default' do %>
                    <i class='glyphicon glyphicon-heart'></i>
                      <%= @post.get_upvotes.size %>
                <%end %>
            <%end %>
            </span>
      </p>

      <!--<a href='#' class='btn btn-xs btn-default'><span class='glyphicon glyphicon-comment'></span> Message</a>-->

      <% if current_user %>
          <%= form_for :relationship, url: relationships_path, html: { method: :post } do |f| %>
              <%= f.hidden_field :invited_id, value: @user.id %>
              <%= f.submit 'follow', class: 'btn btn-xs btn-success',input_html:{rows:1,cols:1} %>
          <% end %>
      <%else%>
          <%= link_to  new_user_session_path do%>
              <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow</button>
          <%end%>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/section/_categories.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h4>Categories</h4>
  </div>
  <ul class='list-group'>
    <% Category.all.each do |category| %>
        <li class='list-group-item'>
          <%= link_to category.name, posts_path(category: category.name)%>
        </li>
    <% end %>
  </ul>
</div>

app/views/posts/section/_cloud_tags.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h4>Cloud Tags</h4>
  </div>
  <div class='panel-body'>
          <span class='' id="tag_cloud">
              <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
                  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
              <% end %>
          </span>
  </div>
</div>

app/views/posts/section/_discussion.html.erb
<div class='discussion' >
  <h4><%= @comments.count %><em>&nbsp;<a name='comments'>Comments</a>&nbsp;</em></h4>
  <hr>
  <!-- Comments -->
  <% if !@comments.blank? %>
      <div id='comments' class="row scroll"><%= render @post.comments %></div>
  <% end %>
  <!--Comment form-->
  <% if user_signed_in? %>
      <%= render 'comments/form' %><!-- comment form-->
  <% else %>
      <h3>Would you like to comment?</h3>
      <h4>You must be a member. <%= link_to ' sign in', new_user_session_path %> if you are already a member.</h4>
  <% end %>
  <hr>
</div>

app/views/posts/section/_my_latest_posts.html.erb
<!-- My Latest Posts -->
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>My Latest Articless</h4>
  </div>
  <ul class="list-group">
    <% @latest_posts.each_with_index do |post,index|%>
        <li class="list-group-item">
          <%= link_to post do %><%= index + 1 %>.
            <%= post.title %> - April 19
          <%end %>
        </li>
    <% end %>
  </ul>

</div>

app/views/posts/section/_related_articles.html.erb
 <div class="top-spacer"></div>
  <% @related_articles.each do | related_article | %>
      <div class='col-sm-6 col-md-6'>
        <% if !related_article.nil? %>
            <div class='thumbnails'>
              <div class='thumbnail'>

                    <%= image_tag(related_article.image.url(:large), class:'img-responsive') %>
                <% end %>
                <h3><%= link_to related_article.title, post_path(related_article) %></h3>
                <% if related_article.excerpt %>
                    <p><%= link_to related_article.excerpt[0..200], post_path(related_article) %></p>
                <% end %>
                  <p align='center'><%= link_to 'Read', post_path(related_article), class:'btn btn-primary btn-block' %></p>
                </div>
              </div>
            </div>

  <% end %>
 <span class="pull-left"><%= paginate(@related_articles) %></span>