config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :posts  do
=begin
    collection do
      get 'search'
    end
=end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  resources :relationships, only: [:create, :destroy, :index]

  get 'tags/:tag' => 'posts#tags', :as => 'tag'
  get 'articles/:author' => 'posts#articles', :as => 'article'

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  acts_as_votable
  acts_as_taggable_on :tags
  is_impressionable


  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 250 }
  validates :category, presence: true
  validates :tag_list, presence: true

  friendly_id :title,use: [:slugged, :history]

  def should_generate_new_friendly_id?
    title_changed? ||new_record? || slug.nil? || slug.blank?
  end


  has_attached_file :image, :styles => { :large => '900x300>',
                                         :medium => '300x300#',
                                         :square => '200x200#',
                                         :thumb => '100x100>' ,
                    :default_url => "/images/:style/missing.png"}

  validates_attachment_content_type :image,
                                    :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_many :comments
  belongs_to :category



  def score
    self.get_upvotes.size - self.get_downvotes.size
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :articles]
  before_filter :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  impressionist :actions=>[:show,:index]

  def index
    #@posts = Post.order('created_at DESC').page(params[:page]).per(3)
    if params[:category].blank?
      @posts = Post.all.order('created_at DESC').page(params[:page]).per(10)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order('created_at DESC').page(params[:page]).per(10)
    end

  end
  def show

    if request.path != post_path(@post)
      redirect_to @post, :status => :moved_permanently
    end

    @comments = Comment.where(post_id: @post.id).order('created_at DESC')
    @related_articles = Post.tagged_with(@post.tag_list, any: true).order('created_at DESC').page(params[:page]).per(2)
    impressionist(@post)

    @user = @post.user
    @latest_posts = Post.where(user_id: @user.id).order('created_at DESC').limit(5)
  end
  def new
    @post = Post.new
    #@categories = Category.all.map{|c| [ c.name, c.id ] }
  end
  def create
    @user = current_user
    @post = @user.posts.build(allowed_params)
   # @post.category_id = params[:category_id]

    if @post.save
      flash[:success] = 'New Post Created'
      redirect_to @post
    else
      render 'new'
    end
  end
  def edit
    redirect_to posts_path unless @post.user == current_user
   # @categories = Category.all.map{|c| [ c.name, c.id ] }
  end
  def update
    if @post.user == current_user
      if @post.update_attributes(allowed_params)
        flash[:success] = 'Updated post'
        redirect_to @post
      else
        render 'edit'
      end
    else
      redirect_to posts_path
      flash[:notice] = 'Action Failed!'
    end
    #@post.category_id = params[:category_id]
  end
  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to posts_path
    else
      redirect_to root_path
      flash[:danger] = 'Action Failed!'
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  def tags
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end
    def articles
      @user = User.find(params[:author])
    if params[:author].present?
      @articles = Post.where(user_id: @user).order('created_at DESC').page(params[:page]).per(10)
    end
  end

  private
  def allowed_params
    params.require(:post).permit(:image, :caption, :title, :excerpt, :body, :category_id, :tag_list, :author)
  end
  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post, multipart: true) do |f| %>
    <div class="row error_message"><%= render 'shared/error_messages', object: f.object %></div>

      <div class="row">
        <!--Media-->
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="box">
            <div class="box-icon">
              <span class="fa fa-4x fa-image"></span>
            </div>
            <div class="info">
              <h5 class="text-left"><span class="text-blue">
                <%= f.input :image, label:'Main Image' %></span></h5>
                <br>
              <h5 class="text-left">
                <%= f.input :caption,label:'Caption: display title on your image',  placeholder: 'Add a caption...',class: 'form-control',input_html: { maxlength: 100 },hint:'max-length 100 characters'%>
              </h5>
              <br>
            </div>
          </div>
        </div>
        <!-- Title & Excerpt-->
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="box">
            <div class="box-icon">
              <span class="fa fa-4x fa-edit"></span>
            </div>
            <div class="info">
              <h5 class="text-left"><%= f.input :title, label:'Title',  placeholder: 'Ex.My Title',class: 'form-control',input_html: { maxlength: 100 },hint:'max-length 100 characters' %>
              </h5>
              <h5 class="text-left"><%= f.input :excerpt, label:'Excerpt',  placeholder: 'My Article\'s Summary',class: 'form-control',input_html: { maxlength: 250 },hint:'max-length 250 characters' %>
              </h5>
            </div>
          </div>
        </div>
    </div><!--End row-->


    <!--Content-->
    <div class="box">
      <div class="info">
        <h5 class="text-left">
          <%= f.input :body, label:'Content', as: :wysihtml5,class: 'wysihtml5', hint:'minimum length 250 characters'%>
        </h5>
      </div>
    </div>

    <!--Filters-->
    <div class="">
      <div class="box">
        <div class="info">
          <!--Slug-->
         <!-- <h5 class="text-left"><%= f.input :slug, label:'Friendly URL',  placeholder: ' Firndly Title',class: 'form-control',input_html: { maxlength: 100 },hint:'max-length 100 characters' %>
          </h5>-->
          <!--Tags-->
          <h5 class="text-left">
            <%= f.input :tag_list,label: 'Tags', class: 'form-control',  placeholder: 'Tags (separated by commas , ). Ex.Sales,Marketing',input_html: { maxlength: 100 },hint: 'max-length 100 characters.' %>
          </h5>
          <!--Categories-->
          <h5 class=" text-left text-blue">Category </h5>
          <h5 class="text-left">
            <%= f.collection_select :category_id, Category.all, :id, :name,{prompt: "Choose a category" }, input_html: { class: "dropdown-toggle" }%>
          </h5>
        </div>
      </div>
    </div>
    <div class="top-spacer"></div>
    <!--Submit button-->
    <%= f.button :submit, 'Publish', class: 'btn btn-primary btn-block btn-lg' %>
<% end %>

app/views/posts/articles.html.erb
<h1>Articles </h1>


<!--/Posts-->
<% provide(:title, 'Home') %>
<% breadcrumb :root %>

<% @articles.each do |p| %>
    <div class="row">
      <br>
      <!-- Left profile -->
      <div class="col-md-2 col-sm-3 text-left">
        <%= link_to user_path(p.user), class:'story-title' do %>
            <%= image_tag(p.user.avatar.url(:thumb),class:'img-circle',style:'width:60px;height:60px') %>
        <%end %>
        <span><br>
          <% if p.user.skill? %>
       <small><%= p.user.skill.titleize %></small>
     <% end %>
   </span><br>

        <!--Social Share  -->
        <div class="pull-right">

          <!-- Facebook -->
          <% if p.user.facebook_acc? %>
              <%= link_to p.user.facebook_acc, class:'btn btn-facebook btn-xs',target:'blank'  do%>
                  <i class="fa fa-facebook"></i>
              <% end %>
          <% end %>
          <!-- Twitter -->
          <% if p.user.twitter_acc? %>
              <%= link_to p.user.twitter_acc, class:'btn btn-twitter btn-xs',target:'blank'  do%>
                  <i class="fa fa-twitter"></i>
              <% end %>
          <% end %>
          <!-- Google+ -->
          <% if p.user.gplus_acc? %>
              <%= link_to p.user.gplus_acc, class:'btn btn-googleplus btn-xs',target:'blank'  do%>
                  <i class="fa fa-google-plus"></i>
              <% end %>
          <% end %>
        </div>
        <!--End oof Social Share-->
      </div>
      <br>
      <!--Right Article-->
      <div class="col-md-7 col-sm-6">
        <div>
          <h3><%= link_to p.title.titleize, post_path(p.id) %></h3>
          <h4>
            <small class='glyphicon glyphicon-user'><%= p.user.name.titleize %></small>
            <% if p.user.country_code?%>
                <small class='glyphicon glyphicon-globe text-muted '><%= p.user.country_name %></small><br>
            <% end %>
            <small style="font-family:courier,'new courier';" class='text-muted'><%=  time_ago_in_words(p.created_at) %> ago
              &nbsp;&nbsp;
              <i class="glyphicon glyphicon-eye-open"></i>
              <%= p.impressionist_count(:filter=>:ip_address) %>
              <%#= p.score "//i.e.usage(like - dislike)//" %>
            </small>
          </h4>
          <small><i>Tags: </i></small> <%= raw (p.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')).titleize %><br>

          <!--<small><i>Category:</i></small> <%#= link_to p.category.name, posts_path(p: p.category.name)%>-->

        </div><br>

        <!--Content-->
        <div class='wrapper'>
          <% if p.excerpt.blank?%>
              <% if p.body.size > 250  %>
                  <p><%= p.body[0..250].html_safe %><small style="font-family:courier,'new courier';"class='text-muted'>
                    <%= link_to '...Continue Reading', post_path(p.id), class:'text-muted'%></small>
                  </p>
              <% else %>
                  <p><%= p.body.html_safe %></p>
              <%end %>
          <% else %>
              <p><%= p.excerpt.html_safe %><small style="font-family:courier,'new courier';" class='text-muted'>
                <%= link_to '...Continue Reading', post_path(p.id), class:'text-muted'%></small>
              </p>
          <% end %>
          <!-- image -->
          <% if p.image.file? %>
              <%= link_to p do %>
                  <%= image_tag(p.image.url(:large), class:"img-responsive") %>
                  <!-- image description content div -->
                  <% if p.caption? %>
                      <div class='caption'>
                        <p class='description_content'><%= p.caption.titleize %></p>
                      </div>
                  <% end %>
              <% end %>
          <% end %>
          <div class='image-footer'>
            <div class='pull-right'>
              <%= link_to  like_post_path(p), method: :put do %>
                  <i class="glyphicon glyphicon-thumbs-up"></i>
                  <%= p.get_upvotes.size %>
              <%end%>
              <%= link_to  dislike_post_path(p), method: :put do %>
                  <i class="glyphicon glyphicon-thumbs-down"></i>
                  <%= p.get_downvotes.size %>
              <%end%>&nbsp;&nbsp;
              <i class="glyphicon glyphicon-share"></i>
            </div>
            <br><br>
          </div>
        </div>
      </div>
    </div>
    <div class="top-spacer"></div>
    <div class="bottom-spacer"></div>
<% end %>

<span class="pull-right"><%= paginate(@articles) %></span>

app/views/posts/edit.html.erb
<% provide(:title, 'Posts') %>
<% breadcrumb :edit_post, @post %>
<h1>Edit Article</h1>
<div class="top-spacer"> </div>
<div class="col-sm-8 col-md-8 center-block">
  <% if @post.image.file? %>
<%#= image_tag(@post.image.url(:medium), class: 'avatar') %>
    <%= image_tag(@post.image.url(:large), class:'img-responsive') %>
  <% end %>

<div class="top-spacer"> </div>
<%= render 'form', post: @post %>

<div class="top-spacer"> </div>
<p><%= link_to 'Delete', @post, method: :delete,
               data: {confirm: "Are you sure you want to delete this permanently?"},class: 'btn btn-danger btn-sm' %></p>
<p><%#= link_to 'back', post_path(@post) %></p>
</div>

app/views/posts/index.html.erb
<!--/Posts-->
<% provide(:title, 'Home') %>
<% breadcrumb :root %>

<% @posts.each do |p| %>
<div class="row dark">
  <br>
  <!-- Left profile -->
  <div class="col-md-2 col-sm-3 text-left">
   <%= link_to user_path(p.user), class:'story-title' do %>
     <%= image_tag(p.user.avatar.url(:thumb),class:'img-circle',style:'width:60px;height:60px') %>
   <%end %>
   <span><br>
     <% if p.user.skill? %>
       <small><%= p.user.skill.titleize %></small>
     <% end %>
   </span><br>

   <!--Social Share  -->
   <div class="pull-right">

      <!-- Facebook -->
     <% if p.user.facebook_acc? %>
         <%= link_to p.user.facebook_acc, class:'btn btn-facebook btn-xs',target:'blank'  do%>
             <i class="fa fa-facebook"></i>
         <% end %>
     <% end %>
      <!-- Twitter -->
     <% if p.user.twitter_acc? %>
         <%= link_to p.user.twitter_acc, class:'btn btn-twitter btn-xs',target:'blank'  do%>
             <i class="fa fa-twitter"></i>
         <% end %>
     <% end %>
      <!-- Google+ -->
     <% if p.user.gplus_acc? %>
         <%= link_to p.user.gplus_acc, class:'btn btn-googleplus btn-xs',target:'blank'  do%>
             <i class="fa fa-google-plus"></i>
         <% end %>
     <% end %>
    </div>
   <!--End oof Social Share-->
  </div>
 <br>
  <!--Article metadata-->
  <div class="col-md-7 col-sm-6">
    <div>
    <h3><%= link_to p.title.titleize, post_path(p.id) %></h3>
    <h4>
      <small class='glyphicon glyphicon-user'><%= p.user.name.titleize %></small>
      <% if p.user.country_code?%>
        <small class='glyphicon glyphicon-globe text-muted '><%= p.user.country_name %></small><br>
          <% end %>
      <small style="font-family:courier,'new courier';" class='text-muted'><%=  time_ago_in_words(p.created_at) %> ago
        &nbsp;&nbsp;
        <i class="glyphicon glyphicon-eye-open"></i>
        <%= p.impressionist_count(:filter=>:ip_address) %>
          <%#= p.score "//i.e.usage(like - dislike)//" %>
      </small>
    </h4>
    <!--<small><i>Tags: </i></small> <%#= raw (p.friendly.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')).titleize %><br>-->

      <!--<small><i>Category:</i></small> <%#= link_to p.category.name, posts_path(p: p.category.name)%>-->

    </div><br>

    <!--Content-->
    <div class='wrapper'>
      <% if p.excerpt.blank?%>
        <% if p.body.size > 250  %>
          <p><%= p.body[0..250].html_safe %><small style="font-family:courier,'new courier';"class='text-muted'>
            <%= link_to '...Continue Reading', post_path(p.id), class:'text-muted'%></small>
          </p>
        <% else %>
          <p><%= p.body.html_safe %></p>
        <%end %>
      <% else %>
        <p><%= p.excerpt.html_safe %><small style="font-family:courier,'new courier';" class='text-muted'>
          <%= link_to '...Continue Reading', post_path(p.id), class:'text-muted'%></small>
        </p>
      <% end %>
      <!-- image -->
      <% if p.image.file? %>
        <%= link_to p do %>
          <%= image_tag(p.image.url(:large), class:"img-responsive") %>
          <!-- image description content div -->
          <% if p.caption? %>
            <div class='caption'>
              <p class='description_content'><%= p.caption.titleize %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <div class='image-footer'>
      <div class='pull-right'>
        <%= link_to  like_post_path(p), method: :put do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>
            <%= p.get_upvotes.size %>
        <%end%>
        <%= link_to  dislike_post_path(p), method: :put do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
            <%= p.get_downvotes.size %>
        <%end%>&nbsp;&nbsp;
        <i class="glyphicon glyphicon-share"></i>
      </div>
      <br><br>
    </div>
  </div>
  </div>
</div>
    <div class="top-spacer"></div>
    <div class="bottom-spacer"></div>
<% end %>

<span class="pull-right"><%= paginate(@posts) %></span>

app/views/posts/new.html.erb
  <% provide(:title, 'New Post') %>
  <% breadcrumb :new_post, @post %>
  <h1>New Article</h1>
  <div class="top-spacer"></div>
  <%= render 'form', post: @post %>

app/views/posts/search.html.erb
<!--
<h1>Articles Search</h1>

<div class='row'>
  <div class="top-spacer"></div>
  <#% @posts.each do |p| %>
      <div class='col-sm-6 col-md-6'>
        <%# if !p.nil? %>
            <div class='thumbnails'>
              <div class='thumbnail'>
                <%# if p.image.file? %>
                    <%#= image_tag(p.image.url(:large), class:'img-responsive') %>
                <%# end %>
                <div class=''>
                  <h3><%#= link_to p.title, post_path(p.id) %></h3>
                  <p><%#= link_to p.excerpt[0..200], post_path(p.id) %></p>
                  <p align='center'><%#= link_to 'Read', p, class:'btn btn-primary btn-block' %></p>
                </div>
              </div>
            </div>
        <%# end %>
      </div>
  <%# end %>
</div>-->

app/views/posts/show.html.erb
<!--  Post Body -->
<% provide(:title, 'Article') %>
<% breadcrumb :post, @post %>
<hr>
  <div class='row'>
    <div class='col-md-8'>
      <article>
        <h1><%= @post.title.titleize %></h1>

        <div class='row'>
          <!--Post metadata-->
          <div class='col-sm-6 col-md-6'>
            <p><small><i>Author: </i><%= @post.user.name.titleize %></small>
              &nbsp;&nbsp;<span class='glyphicon glyphicon-time'>&nbsp;</span><%= time_ago_in_words(@post.created_at)%> ago
            </p>
            <% if @post.user == current_user %>
              <small class='btn btn-inverse' ><%= link_to edit_post_path(@post) do %>
                <i class='glyphicon glyphicon-edit'></i>
              <%end %>
              </small>
              | <small class='btn btn-inverse'><%= link_to  @post, method: :delete,
                         data: {confirm: 'Are you sure you want to delete this permanently?'} do %>
                <i class='glyphicon glyphicon-trash'></i>
              <% end %>
              </small>
            <% end %>
          </div>
          <div class='col-sm-6 col-md-6'>
            <a href='#comments'><%= @comments.count %> Comments</a>&nbsp;&nbsp;
            <%= link_to  like_post_path(@post), method: :put do %>
                <i class='glyphicon glyphicon-thumbs-up'></i>
                <%= @post.get_upvotes.size %>
            <%end%>
            <%= link_to  dislike_post_path(@post), method: :put do %>
                <i class='glyphicon glyphicon-thumbs-down'></i>
                <%= @post.get_downvotes.size %>
            <%end%>
            &nbsp;&nbsp;
                <i class='glyphicon glyphicon-eye-open'></i>
                <%= @post.impressionist_count(:filter=>:ip_address) %>
            </div>
        </div>
        <hr>
        <!--Main image-->
          <% if @post.image.file? %>
            <%= image_tag(@post.image.url(:large), class:'img-responsive') %>
          <% end %>
          <br />
          <!--Content-->
          <% if @post.excerpt.present? %><!--Excerpt-->
            <p class="lead"><%= @post.excerpt  %><p>
          <% end %>
          <div class="top-spacer"></div>
          <p><%= @post.body.html_safe %></p><!--Body>
          <!--Tags-->
          <% @post.tags.any? %>
            <% @post.tags.each do |tag| %>
              <span class='label label-primary'><%= link_to tag.name, tag_path(tag.name),class: ' text-white' %></span>
      </article>
      <hr>
      <!-- Discussion Section -->
      <%= render 'posts/section/discussion' %>
      <!--Related Articles-->
      <% if !@related_articles.blank? %>
         <h4> Related Articles</h4><h6 class="pull-right"><i><%= link_to'View All', tag_path(tag.name) %> </i></h6>
      <% end %>
      <div class="top-spacer"></div>
        <% end %>
      <%= render 'posts/section/related_articles' %>
    </div><!-- End main post-->

    <!--Sidebar-->
    <div class='col-md-4'>
      <!--About Me-->
      <%= render 'posts/section/about' %>
      <!-- My Latest Posts -->
      <%= render 'posts/section/my_latest_posts' %>
      <!-- Cloud Tags -->
      <%= render 'posts/section/cloud_tags' %>
      <!-- Categories -->
      <%= render 'posts/section/categories' %>
    </div>
  </div>

app/views/posts/tags.html.erb
<!--/Posts-->
<% provide(:title, 'Home') %>
<% breadcrumb :root %>
<% @posts.each do |p| %>
    <div class="row">
      <br>
      <div class="col-md-2 col-sm-3 text-left">

        <%= link_to user_path(p.user), class:"story-title" do %>
            <%= image_tag(p.user.avatar.url(:thumb),class:"img-circle",style:"width:60px;height:60px") %>
        <%end %>
        <p><small><%= p.user.name.titleize %></small></p>
        <p><small><%= p.user.skill.titleize %></small></p>
        <%= link_to  like_post_path(p), method: :put do %>
            <i class="glyphicon glyphicon-thumbs-up"></i>
            <%= p.get_upvotes.size %>
        <%end%>
        <%= link_to  dislike_post_path(p), method: :put do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
            <%= p.get_downvotes.size %>
        <%end%>
      </div>

      <div class="col-md-8 col-sm-9">
        <h3><%= link_to p.title.titleize, post_path(p.id) %></h3>
        <h4><small style="font-family:courier,'new courier';" class="text-muted"><%=  time_ago_in_words(p.created_at) %> ago
          • <%= link_to 'Posted from Brazil', post_path(p.id), class:"text-muted"%>
          &nbsp;&nbsp;
          <%= link_to  posts_path, method: :put do %>
              <i class="glyphicon glyphicon-eye-open"></i>
              <%= p.score %>
          <%end%>
        </small>
        </h4>
        <h4><span class="label label-default"><%#= p.tag %></span></h4>


        <% if p.excerpt.blank?%>
            <% if p.body.size > 250  %>
                <p><%= p.body[0..250].html_safe %><small style="font-family:courier,'new courier';"class="text-muted">
                  <%= link_to '...Continue Reading', post_path(p.id), class:"text-muted"%></small>
                </p>
            <% else %>
                <p><%= p.body.html_safe %></p>

            <%end %>
        <% else %>
            <p><%= p.excerpt.html_safe %><small style="font-family:courier,'new courier';"class="text-muted">
              <%= link_to '...Continue Reading', post_path(p.id), class:"text-muted"%></small>
            </p>
        <% end %>

        <% if p.image.file? %>
            <%= link_to p do %>
                <%= image_tag(p.image.url(:large), class:"img-responsive") %>
            <% end %>
        <% end %>
        <div class="top-spacer"></div>

        <!--Social Share  -->
        <div class="pull-right">

          <!-- Facebook -->
          <a href="https://www.facebook.com/sharer/sharer.php?u=" title="Share on Facebook" target="_blank" class="btn btn-facebook btn-xs"><i class="fa fa-facebook"></i></a>
          <!-- Twitter -->
          <a href="http://twitter.com/home?status=" title="Share on Twitter" target="_blank" class="btn btn-twitter btn-xs "><i class="fa fa-twitter"></i></a>
          <!-- Google+ -->
          <a href="https://plus.google.com/share?url=" title="Share on Google+" target="_blank" class="btn btn-googleplus btn-xs"><i class="fa fa-google-plus"></i></a>
          <!-- LinkedIn -->
          <a href="http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=" title="Share on LinkedIn" target="_blank" class="btn btn-linkedin btn-xs"><i class="fa fa-linkedin"></i></a>
        </div>
        <!--End oof Social Share-->

        <div class="row">
          <div class="col-xs-9"></div>
          <div class="col-xs-3"></div>
        </div>
        <br><br>
      </div>
    </div>
    <hr>
<% end %>
<%#= paginate(@posts) %>