config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :posts  do
=begin
    collection do
      get 'search'
    end
=end
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  resources :relationships, only: [:create, :destroy, :index]

  get 'tags/:tag' => 'posts#tags', :as => 'tag'
  get 'articles/:author' => 'posts#articles', :as => 'article'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
<% end %>

<script>
    $('.alert').fadeOut(4000);
</script>

app/views/layouts/_footer.html.erb
<hr>

<div class="container" id="footer">
  <div class="row">
    <div class="col col-sm-12">

      <h1>Follow Us</h1>
      <div class="btn-group">
        <a class="btn btn-twitter btn-lg" href="https://twitter.com/uopeople"target="_blank"><i class="icon-twitter icon-large"></i> Twitter</a>
        <a class="btn btn-facebook btn-lg" href="https://www.facebook.com/UoPeople" target="_blank"><i class="icon-facebook icon-large"></i> Facebook</a>
        <a class="btn btn-google-plus btn-lg" href="https://plus.google.com/102391203006890407038/posts" target="_blank"><i class="icon-google-plus icon-large"></i> Google+</a>
      </div>

    </div>
  </div>
</div>

<hr>

<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline">
          <li><i class="icon-facebook icon-2x"></i></li>
          <li><i class="icon-twitter icon-2x"></i></li>
          <li><i class="icon-google-plus icon-2x"></i></li>
          <li><i class="icon-pinterest icon-2x"></i></li>
        </ul>

      </div>
      <div class="col-sm-6">
        <p class="pull-right">made by <i class="icon-heart-empty"></i><a href="http://www.tekwin.org">Adam Debbagh</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to "Home", root_path, class: 'navbar-brand' %>

        <% if current_user %>
            <%= link_to new_post_path do %>
                  <span class=" glyphicon glyphicon-edit navbar-brand"><strong>New</strong></span>
                  <% end %>
        <% else %>
            <%= link_to 'Login', new_user_session_path,class: 'navbar-brand' %>
        <% end %>
      <!--new Post -->

    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-right navbar-nav">
        <% if current_user %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %>&nbsp;&nbsp;
                    <span class="round-image-50 pull-right"><%= image_tag(current_user.avatar.url(:thumb)) %></span>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to edit_user_registration_path do %>
                        Account Settings<span class=" glyphicon glyphicon-cog pull-right"></span>
                        <% end %></li>
                    <li class="divider"></li>
                    <li><%= link_to user_path(current_user) do %>
                        User Profile <span class=" glyphicon glyphicon-stats pull-right"></span>
                        <% end %></li>
                    <li class="divider"></li>
                    <li><%= link_to  relationships_path do %>
                        Followers<span class=" glyphicon glyphicon-heart pull-right"></span>
                        <% end %></li>
                    <li class="divider"></li>
            <!--<li><a href="#">Messages <span class="badge pull-right"> 42 </span></a></li>
            <li class="divider"></li>
            <li><a href="#">Favourites Snippets <span class="glyphicon glyphicon-heart pull-right"></span></a></li>
            <li class="divider"></li>-->
                    <li><%= link_to destroy_user_session_path, method: :delete do %>
                        Sign Out<span class=" glyphicon glyphicon-log-out pull-right"></span>
                    <% end %></li>
                </ul>
            </li>
            <% end %>
      </ul><!--user menu-->
      <ul class="nav navbar-right navbar-nav">
        <li><%= link_to 'Members', users_path %></li>
      </ul><!--Members-->

     <!-- <ul class="nav navbar-right navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-search"></i></a>
          <ul class="dropdown-menu" style="padding:12px;">
            <%#= form_for( search_posts_path, method: :get, role: 'search', class:'form-inline') do  %>
                <p>
                  <%#= text_field_tag :search, params[:search], class: 'form-control' %>
                  <%#= submit_tag 'Go', name: nil,class:'btn  btn-danger btn-xs' %>
                </p>
            <%# end %>

            &lt;!&ndash; <form class="form-inline">
              <button type="submit" class="btn btn-default pull-right">
              <i class="glyphicon glyphicon-search"></i></button>
              <input type="text" class="form-control pull-left" placeholder="Search">
            </form>&ndash;&gt;
          </ul>
        </li>
      </ul>--><!--Search bar-->

    </nav>
  </div>
</header>

<div id="masthead">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1><%= link_to 'Discus', posts_path %>sed
          <br><p class="lead">already..!</p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg">
          <div class="row ">
            <div class="col-sm-12 text-center"><h3>University of the People</h3>

                <%= link_to 'http://uopeople.edu/',target:'blank' do %>
                  <%= image_tag 'applynow.jpg' %>
             <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /cont -->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"></div>
      </div>
    </div>
  </div><!-- /cont -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menu'%>
<%= render 'layouts/flash_messages'%>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-body">
          <%= breadcrumbs pretext: "",

                          style: :bootstrap,
                          separator: "",
                          link_curren: true,
                          semantic: true%>
  <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer'%>
</body>
</html>